export default {
  bpm: 1.42,
  created_at: '2000-01-01T12:00:00Z',
  isrc: 'string',
  has_chords: true,
  length: 1,
  meter: 'string',
  name: 'string',
  notes: 'string',
  print_margin: 'string',
  print_orientation: 'string',
  print_page_size: 'string',
  updated_at: '2000-01-01T12:00:00Z',
  chord_chart: 'string',
  chord_chart_font: 'string',
  chord_chart_key: 'string',
  chord_chart_columns: 1,
  chord_chart_font_size: 1,
  has_chord_chart: true,
  lyrics_enabled: true,
  number_chart_enabled: true,
  numeral_chart_enabled: true,
  sequence: [],
  sequence_short: [],
  chord_chart_chord_color: 1,
  archived_at: '2000-01-01T12:00:00Z',
  lyrics: 'string',
  rehearsal_mix_id: 'primary_key',
  song: {
    jsonApi: 'hasOne',
    type: 'Song',
  },
};
