export default {
  created_at: '2000-01-01T12:00:00Z',
  first_name: 'string',
  last_name: 'string',
  name_prefix: 'string',
  name_suffix: 'string',
  updated_at: '2000-01-01T12:00:00Z',
  anniversary: '2000-01-01T12:00:00Z',
  birthdate: '2000-01-01T12:00:00Z',
  given_name: 'string',
  middle_name: 'string',
  nickname: 'string',
  facebook_id: 'primary_key',
  photo_url: 'string',
  photo_thumbnail_url: 'string',
  full_name: 'string',
  permissions: 'string',
  status: 'string',
  legacy_id: 'primary_key',
  ical_code: 'string',
  logged_in_at: '2000-01-01T12:00:00Z',
  notes: 'string',
  passed_background_check: true,
  site_administrator: true,
  max_permissions: 'string',
  me_tab: 'string',
  plans_tab: 'string',
  songs_tab: 'string',
  media_tab: 'string',
  people_tab: 'string',
  created_by: {
    type: 'Person',
    jsonApi: 'hasOne',
  },
  updated_by: {
    type: 'Person',
    jsonApi: 'hasOne',
  },
};
